replicaCount: 1

image:
  repository: postgres
  tag: latest

service:
  type: NodePort
  port: 5432
  nodePort: 5432
  externalIP: "192.168.1.140"

persistence:
  enabled: true
  storageClass: "hostpath"
  accessMode: ReadWriteOnce
  size: 5Gi
