apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: [ 'sh', '-c', 'until nc -z -v -w30 mysql 3306; do echo "Waiting for MySQL..."; sleep 5; done; echo "MySQL is up!"' ]
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: FLASK_ENV
              value: development
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: dev
            - name: DB_USER
              value: dev
            - name: DB_PASSWORD
              value: dev
          ports:
            - containerPort: 5000
          readinessProbe:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - "mysql -h $DB_HOST -P $DB_PORT -u $DB_USER -p$DB_PASSWORD -e 'SELECT 1' > /dev/null 2>&1"
            initialDelaySeconds: 5
            periodSeconds: 10