apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: jaeger-ui
              containerPort: 16686
              protocol: TCP
            - name: grpc-col-4317
              containerPort: 4317
              protocol: TCP
            - name: grpc-col-4318
              containerPort: 4318
              protocol: TCP
            - name: thr-udp-6831
              containerPort: 6831
              protocol: UDP
            - name: thr-udp-6832
              containerPort: 6832
              protocol: UDP
            - name: zipkin-http
              containerPort: 9411
              protocol: TCP
            - name: oth-5775
              containerPort: 5775
              protocol: TCP
            - name: oth-5778
              containerPort: 5778
              protocol: TCP
            - name: oth-14250
              containerPort: 14250
              protocol: TCP
            - name: oth-14267
              containerPort: 14267
              protocol: TCP
            - name: oth-14268
              containerPort: 14268
              protocol: TCP
          env:
            - name: LOG_LEVEL
              value: "debug"
            - name: COLLECTOR_ZIPKIN_HTTP_PORT
              value: "9411"
