# region Database configuration

# ELASTIC SEARCH
ELASTICSEARCH_CERT_PATH = 'es-cert.crt'
ELASTICSEARCH_HOST = 'https://10.30.11.14:9200'
ELASTICSEARCH_USERNAME = 'elastic'
ELASTICSEARCH_PASSWORD = 'YTrEkQ9G8OzH5rQi1wgK'
ELASTICSEARCH_INDEX = 'workers'

# endregion
