# Number of MySQL replicas
replicaCount: 1

# Image settings
image:
  repository: mysql
  tag: "8.0"

# MySQL credentials and database setup
mysqlRootPassword: dev
mysqlDatabase: dev
mysqlUser: dev
mysqlPassword: dev

appVersion: "8.0"

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi
  storageClass: ""

service:
  type: ClusterIP
  port: 3306
