apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: kafka-ui
  externalIPs:
    - {{ .Values.service.externalIP }}