replicaCount: 1

image:
  repository: jaegertracing/all-in-one
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  externalIP: "192.168.1.140"
  ports:
    - name: jaeger-ui
      port: 16686
      targetPort: 16686
      protocol: TCP
    - name: grpc-col-4317
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: grpc-col-4318
      port: 4318
      targetPort: 4318
      protocol: TCP
    - name: thr-udp-6831
      port: 6831
      targetPort: 6831
      protocol: UDP
    - name: thr-udp-6832
      port: 6832
      targetPort: 6832
      protocol: UDP
    - name: zipkin-http
      port: 9411
      targetPort: 9411
      protocol: TCP
    - name: oth-5775
      port: 5775
      targetPort: 5775
      protocol: TCP
    - name: oth-5778
      port: 5778
      targetPort: 5778
      protocol: TCP
    - name: oth-14250
      port: 14250
      targetPort: 14250
      protocol: TCP
    - name: oth-14267
      port: 14267
      targetPort: 14267
      protocol: TCP
    - name: oth-14268
      port: 14268
      targetPort: 14268
      protocol: TCP
