# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5044
          volumeMounts:
            - name: log-directory
              mountPath: /logs  # Inside the container
            - name: logstash-config
              mountPath: {{ .Values.logstashConfig.configPath }}
              subPath: logstash.conf
      volumes:
        - name: log-directory
          hostPath:
            path: {{ .Values.logDirectory }}
            type: Directory
        - name: logstash-config
          configMap:
            name: logstash-config
