replicaCount: 3

image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  tag: "8.5.1"

service:
  type: ClusterIP
  port: 9200

persistence:
  enabled: true
  storageClass: "hostpath"
  accessMode: ReadWriteOnce
  size: 5Gi
