replicaCount: 1

image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  tag: "8.5.1"

service:
  type: ClusterIP
  port: 9200

persistence:
  enabled: true
  storageClass: "hostpath"
  accessMode: ReadWriteOnce
  size: 5Gi

# Disable security in Elasticsearch
extraEnv:
  - name: discovery.type
    value: "single-node"
  - name: ES_JAVA_OPTS
    value: "-Xms512m -Xmx512m"
  - name: xpack.security.enabled
    value: "false"
  - name: xpack.security.http.ssl.enabled
    value: "false"
  - name: xpack.security.transport.ssl.enabled
    value: "false"