replicaCount: 1

image:
  repository: docker.elastic.co/kibana/kibana
  tag: "8.5.1"

service:
  type: ClusterIP
  port: 5601

extraEnv:
  - name: ELASTICSEARCH_HOSTS
    value: "http://elasticsearch:9200"
  - name: XPACK_SECURITY_ENABLED
    value: "false"