replicaCount: 1

image:
  repository: docker.elastic.co/kibana/kibana
  tag: "8.5.1"

service:
  type: NodePort
  port: 5601
  nodePort: 5601
  externalIP: "192.168.1.140"

extraEnv:
  - name: ELASTICSEARCH_HOSTS
    value: "http://elasticsearch:9200"
  - name: XPACK_SECURITY_ENABLED
    value: "false"