apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  type: {{ .Values.service.type }}

  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9200
  selector:
    app: elasticsearch
