# values.yaml

replicaCount: 1

image:
  repository: docker.elastic.co/logstash/logstash
  tag: "8.5.1"

service:
  type: ClusterIP
  port: 5044

logDirectory: "/home/bogdan/workspace/dev/frameworks/etl-kafka/framework-pipeline-etl/logs"  # Replace with the actual path

logstashConfig:
  enabled: true
  configPath: "/usr/share/logstash/pipeline/logstash.conf"
