version: '3.8'

services:
  backend:
    image: service-kafka-pipeline-editor:latest
    network_mode: host
    environment:
      - FLASK_ENV=development
      - DB_HOST=172.17.120.18
      - DB_PORT=3306
      - DB_NAME=dev
      - DB_USER=dev
      - DB_PASSWORD=dev
    depends_on:
      database:
        condition: service_healthy

  frontend:
    image: kafka-workers-visualizer:latest
    network_mode: host
    env_file:
      - ./kafka-workers-visualizer/.env
    depends_on:
      - backend

  database:
    image: mysql:8.0
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
