replicaCount: 1

image:
  repository: localhost:32000/kafka-workers-visualizer
  tag: latest

service:
  type: NodePort
  port: 80
  nodePort: 80
  externalIP: "192.168.1.140"

env:
  REACT_APP_API_BASE_URL: "/api"