replicaCount: 1

image:
  repository: localhost:32000/kafka-workers-visualizer
  tag: "latest"
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  nodePort: 3033

ingress:
  enabled: false

resources: {}
