apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: "mysql:{{ .Values.appVersion }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.mysqlRootPassword }}"  # Added quotes for safety
            - name: MYSQL_DATABASE
              value: "{{ .Values.mysqlDatabase }}"  # Added quotes
            - name: MYSQL_USER
              value: "{{ .Values.mysqlUser }}"  # Added quotes
            - name: MYSQL_PASSWORD
              value: "{{ .Values.mysqlPassword }}"  # Added quotes
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
