apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
data:
  init.sql: |
    CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY '{{ .Values.mysqlRootPassword }}';
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;

    CREATE USER IF NOT EXISTS '{{ .Values.mysqlUser }}'@'%' IDENTIFIED BY '{{ .Values.mysqlPassword }}';
    GRANT ALL PRIVILEGES ON *.* TO '{{ .Values.mysqlUser }}'@'%' WITH GRANT OPTION;

    FLUSH PRIVILEGES;