apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3306
      protocol: TCP
  selector:
    app: mysql
  externalIPs:
    - {{ .Values.service.externalIP }}